languageCode = "en-us"
title = "Military Hacks"
[permalinks]
  blog = "/:slug/"
  pages = "/:slug/"
  army = "/:slug/"
  navy = "/:slug/"
  air-force = "/:slug/"
  marines = "/:slug/"
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
